Improved dependecy-checks. Cleanup

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -1,21 +1,51 @@
 #!/bin/sh
-# $Id: configure,v 1.3 2000/12/20 14:30:32 michael Exp $
+# $Id: configure,v 1.4 2001/05/10 23:51:38 michael Exp $
 # Parse the config-File and create a sed-Script out of it.
 
+CONF_RAW=config
 CONF_FILE=config.sed
 
-THISDIR=`pwd`
-# Generate the sed-file
-grep -Ev "^#" config | grep -Ev "^$" | \
-sed -e "s/{\t| }//g"  | tr '=' ' ' | sed "s|:|\\\:|" |\
-  awk '{print "s:<%%"$1"%%>:"$2":" }' > config.sed
+THISDIR=$(pwd)
 
-# Create the Makefiles
-for foo in include www www/pics commands man
-do
-    cd ${foo}
-    echo "Creating Makefile in ${foo}";
-    cat Makefile.raw | sed -f ${THISDIR}/${CONF_FILE} > Makefile
-    cd ${THISDIR}
+check_prereq () {
+    # Check if we can find all neccessary tools:
+    echo -n "Checking for '$1': ... "
+    req=$(which "$1")
+    if [ -n "${req}" ] ; then 
+        # Found.
+        echo "Found - $req"
+    else
+        echo "Not Found!"
+        exit 2
+    fi
+}
+
+make_makefiles () {
+    # Generate Makefiles in Directory $1
+    ( 
+        echo -n "Generating Makefile in ./$1 ... ";
+        cd "$1";
+        sed -f ${THISDIR}/${CONF_FILE} Makefile.raw > Makefile
+        echo "Done."
+    )
+}
+
+# Let's see if we can find all required tools:
+TOOLS="sed awk"
+for foo in ${TOOLS} ; do 
+  check_prereq ${foo}
 done
 
+# Generate the sed-file
+grep -Ev "^#" ${CONF_RAW} | grep -Ev "^$" | \
+  sed -e "s/{\t| }//g"  | tr '=' ' ' | sed "s|:|\\\:|" |\
+  awk '{print "s:<%%"$1"%%>:"$2":" }' > ${CONF_FILE}
+
+# Create the Makefiles
+SUBDIRS="include www www/pics commands man"
+for foo in ${SUBDIRS}
+do
+    make_makefiles "${foo}"
+done
+
+exit 0
